apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manager
  namespace: openshift-gitops
  annotations:
    "helm.sh/hook-weight": "3"
spec:
  generators:
    - list:
        elements:
          - cluster: labo1
            url: 'https://kubernetes.default.svc'
          - cluster: engineering-prod
            url: 'https://2.4.6.8'
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: 'manager'
    spec:
      destination:
        namespace: openshift-gitops
        server: '{{ "{{ url }}" }}'
      project: default
      source:
        path: applicationset
        repoURL: 'https://gitlab.com/mascolo99/argocd.git'
        targetRevision: HEAD
        directory:
          recurse: true
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true