apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: workersautoscaling
  namespace: openshift-machine-api
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: cluster-v88mn-ljkdx-worker-us-east-2c